apiVersion: v1
kind: Service
metadata:
  name: data-source-interaction
spec:
  selector: 
    app: data-source-interaction
  type: NodePort
  ports:
     - port: 3011
       targetPort: 3011
       nodePort: 3011
