version: '2'
services:
  kafka-zookeeper:
    image: openzipkin/zipkin-kafka:1.18.0
    container_name: kafka-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PORT: 9094
    ports:
      - "127.0.0.1:2182:2181"
      - "127.0.0.1:9094:9092"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  data-source-interaction:
    build: .
    image: gridvo/data-source-interaction:dev
    container_name: data-source-interaction
    ports:
      - "127.0.0.1:3150:3150"
      - "127.0.0.1:3011:3011"
    depends_on:
     - zookeeper
     - kafka
    environment:
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181